name: Java CI with Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build and package Java code
        run: |
          mvn package -Dmaven.test.skip=true
          mkdir docker
          cp ./Dockerfile ./docker
          cp ./target/*.jar ./docker
          cd docker
          docker build -t docker-demo .
          
          docker login --username=aliyun9272912629 registry.cn-hangzhou.aliyuncs.com
          docker push docker-demo
          

