name: YY CI-CD 流水线

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Package and upload the image
        run: |
          mvn package -Dmaven.test.skip=true
          mkdir docker
          cp ./Dockerfile ./docker
          cp ./target/*.jar ./docker
          cd docker
          docker login --username=aliyun5935525038 --password=xzq0511./ registry.cn-hangzhou.aliyuncs.com
          docker build . --file Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/yuechu-docker-demo/docker-demo:2.4.1
          docker push registry.cn-hangzhou.aliyuncs.com/yuechu-docker-demo/docker-demo:2.4.1

      - name: Connect to the server and run the image
        uses: appleboy/ssh-action@master
        with:
          # 同上述
          host: 43.139.111.22
          username: root
          password: K7#sF9@2w5
          port: 22
          # 拉镜像 运行
          script: |
            docker stop docker-demo 
            docker rm -f docker-demo
            docker pull registry.cn-hangzhou.aliyuncs.com/yuechu-docker-demo/docker-demo:2.4.1
            docker run -d -p 8012:8012 -p 8012:8012 --name docker-demo registry.cn-hangzhou.aliyuncs.com/yuechu-docker-demo/docker-demo:2.4.1
            



     



